module.exports.descriptors = [
    'Colossal',
    'Core',
    'Berserker',
    'Roaring',
    'Legendary',
    'Herculean',
    'Bold',
    'Big Muscle',
    'Atlas',
    'Maple',
    'Misty',
    'Stamina',
    'Epic',
    'Fitness',
    'Power House',
    'Sky',
    'Dusty',
    'Exalted'
]

module.exports.places = [
    'Room',
    'House',
    'Maniacs',
    'Masters',
    'Group Gym',
    'Static Gym',
    'Ghost Gym',
    'Gym',
    'Dispersed Gym',
    'Backcountry Gym',
    'Nation',
    'Works',
    'Palace',
    'Gymnasium',
    'Studio',
    'Performance',
    'Sandy Gym',
    'Mule Gym',
    'Hunting Gym',
    'Scruff',
    'Enterprise'
]
